version: '3.7'
services:
  test_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'test_app'
    ports:
      - 8090:80
      - 8044:443
    depends_on:
      - test_db
    volumes:
      - ../test:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  test_db:
    image: mariadb:10.1.48
    restart: always
    ports:
      - "3368:3306"
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "pass"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql