version: '3.7'
services:
  test_task_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'test_task_app'
    container_name: 'test_task_app'
    ports:
      - 8090:80
    depends_on:
      - test_task_db
    volumes:
      - ../test:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  test_task_db:
    container_name: 'test_task_db'
    image: mysql:5.7.12
    restart: always
    ports:
      - "3367:3306"
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_USER: "testdb"
      MYSQL_PASSWORD: "pass"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql